package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/LOCATION_FORWARD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /System/Volumes/Data/jenkins/workspace/8-2-build-macosx-x86_64/jdk8u333/2551/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, April 26, 2022 6:42:08 AM BST
*/

public interface LOCATION_FORWARD
{

  /**
     * Indicates a LocationForward reply status. One possible value for 
     * <code>RequestInfo.reply_status</code>.
     * @see RequestInfo#reply_status
     * @see SUCCESSFUL
     * @see SYSTEM_EXCEPTION
     * @see USER_EXCEPTION
     * @see TRANSPORT_RETRY
     */
  public static final short value = (short)(3);
}
